[character]
error_symbol = "[➜](bold red)"
success_symbol = "[➜](bold green)"
vicmd_symbol = "[➜](bold yellow)"

[directory]
style = "bold blue"

[cmd_duration]
format = "[](purple) [$duration]($style) "

[python]
symbol = "󰌠 "

[lua]
symbol = " "
